### ISSUE TITLE
Removing "awaiting response" label from adapters

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/actions#35]
> [this action](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/triage-labels.yml) needs to be copied over to the adapter plugin repos - it's just in dbt-core right now
> or moved into the [centralized actions repo](https://github.com/dbt-labs/actions), and then pulled into the others

### Quickest solution
Copy [this action](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/triage-labels.yml) over to each adapter plugin repos

### Best solution
1. Add [this action](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/triage-labels.yml) to the [centralized actions repo](https://github.com/dbt-labs/actions)
1. Pull it into dbt-core + each adapter
1. Remove the original action from dbt-core

**Comment by emmyoop** [comment]
First, 100% agree this needs to be added to adapters.  That's not the purpose of my comment.  My comment is more generally process related.  Tagging @leahwicz and @lostmygithubaccount to see if they have opinions here.

This is a good time to have the discussion on when to centralize actions.  This action is just a single step job to a marketplace action

```
jobs:
  triage_label:
    if: contains(github.event.issue.labels.*.name, 'awaiting_response')
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "triage"
          remove-labels: "awaiting_response"
```

It may be worth centralizing so that if we change the labels for some reason we do it in only one place.  Or if we update the version of the actions we want to use (we really shouldn't blindly point to master) we could do it in a single place.

But do we want to centralize workflows that are single step workflows like this?  There are others that we could centralize that I have not because I was trying to avoid layering too deep but I'm not sure that's a great reason.  When you make it a reusable workflow the workflow steps show in your local run so all the debug info is available, unlike when you're using a marketplace action and it's a bit of a blackbox.

After typing this up, I'm leaning towards centralizing anything we use across core and adapters if for no other reason that to control the versions we're using in a singular place.
